### PR TITLE
Fix Logo and Explore button

### PR DESCRIPTION
**Pull request by MayaSatishRao**
I have made Snippets logo as a Link so that when it is clicked it takes the user to home page. I also checked the Explore button a nd it was not take the user to browse page. So, I made that as well.

### CODE REVIEW

**Comment by A-BMT02** [comment]
I made some comments on your pull request @MayaSatishRao 
Thank you for checking out the project and contributing!

**Review by MayaSatishRao — COMMENTED** [review]
In my previous commit, I had tried to comment 12th line which was not required. I have made removed /* and */ int this commit

**Review by MayaSatishRao — COMMENTED** [review]
In the previous commit, the opening tag of Link was present two times. I have removed them in this commit.

**Comment by A-BMT02** [comment]
Everything looks great now!
I'll go ahead and merge the pr

Thank you for contributing @MayaSatishRao!

**Pull request merged**
